from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from io import BytesIO
from typing import Any

import qrcode

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
)


def _make_verification_qr(report_id: str) -> BytesIO:
    """Create an in-memory QR code for report verification."""
    verification_url = f"https://oimlense.vercel.app/verify/{report_id}"
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=8,
        border=2,
    )
    qr.add_data(verification_url)
    qr.make(fit=True)

    image = qr.make_image(fill_color="black", back_color="white")
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)

    return buffer

    image = qr.make_image(fill_color="black", back_color="white")
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)

    return buffer


def _value(value: Any, default: str = "—") -> str:
    if value is None or value == "":
        return default

    if isinstance(value, Decimal):
        return str(value)

    if isinstance(value, float):
        return f"{value:g}"

    if isinstance(value, datetime):
        return value.strftime("%d-%m-%Y %H:%M")

    return str(value)


def _format_date(value: Any) -> str:
    if not value:
        return "—"

    try:
        if isinstance(value, str):
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
            return parsed.strftime("%d-%m-%Y")
        if isinstance(value, datetime):
            return value.strftime("%d-%m-%Y")
    except Exception:
        pass

    return _value(value)


def _result_status(value: Any) -> str:
    value = str(value or "MANUAL_REVIEW").upper()

    if value == "PASS":
        return "PASS"
    if value == "FAIL":
        return "FAIL"
    if value == "NOT_APPLICABLE":
        return "N/A"

    return "MANUAL REVIEW"


def _overall_result(session: dict[str, Any], results: list[dict[str, Any]]) -> str:
    session_result = str(session.get("final_result") or "").upper()

    if session_result in {
        "PASS",
        "FAIL",
        "NOT_APPLICABLE",
        "MANUAL_REVIEW",
    }:
        return _result_status(session_result)

    statuses = [
        str(item.get("result_status") or "").upper()
        for item in results
    ]

    if any(status == "FAIL" for status in statuses):
        return "FAIL"

    if any(status == "MANUAL_REVIEW" for status in statuses):
        return "MANUAL REVIEW"

    if statuses and all(status in {"PASS", "NOT_APPLICABLE"} for status in statuses):
        return "PASS"

    return "MANUAL REVIEW"


def _header_footer(canvas, doc):
    canvas.saveState()

    width, height = A4

    # Header line
    canvas.setStrokeColor(colors.HexColor("#D6B85A"))
    canvas.setLineWidth(1.2)
    canvas.line(18 * mm, height - 17 * mm, width - 18 * mm, height - 17 * mm)

    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(colors.HexColor("#444444"))
    canvas.drawString(
        18 * mm,
        height - 13 * mm,
        "OIMLENSE — NAWI TEST REPORT",
    )

    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(
        width - 18 * mm,
        height - 13 * mm,
        "OIML R 76",
    )

    # Footer
    canvas.setStrokeColor(colors.HexColor("#DDDDDD"))
    canvas.setLineWidth(0.5)
    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm,
    )

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#666666"))

    canvas.drawString(
        18 * mm,
        9 * mm,
        "Generated by OIMLense",
    )

    canvas.drawRightString(
        width - 18 * mm,
        9 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


def generate_r76_report(
    *,
    session: dict[str, Any],
    instrument: dict[str, Any],
    environment: list[dict[str, Any]],
    equipment: list[dict[str, Any]],
    results: list[dict[str, Any]],
    observations: list[dict[str, Any]] | None = None,
) -> BytesIO:

    observations = observations or []

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=20 * mm,
        title="OIMLense NAWI Test Report",
        author="OIMLense",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#202020"),
        spaceAfter=5 * mm,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#666666"),
        spaceAfter=8 * mm,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#222222"),
        spaceBefore=5 * mm,
        spaceAfter=3 * mm,
    )

    normal_style = ParagraphStyle(
        "NormalSmall",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#333333"),
    )

    small_style = ParagraphStyle(
        "Small",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=9.5,
        textColor=colors.HexColor("#444444"),
    )

    story = []

    # ---------------------------------------------------------
    # REPORT HEADER
    # ---------------------------------------------------------

    story.append(Spacer(1, 3 * mm))

    report_id = (
        session.get("report_id")
        or f"R76-{str(session.get("session_number") or session.get("id", "REPORT"))[:20]}"
    )

    qr_image = _make_verification_qr(report_id)

    qr_flowable = Image(
        qr_image,
        width=25 * mm,
        height=25 * mm,
    )

    header_title = [
        Paragraph(
            "OIMLENSE",
            title_style,
        ),
        Paragraph(
            "TEST REPORT FOR NON-AUTOMATIC WEIGHING INSTRUMENT",
            subtitle_style,
        ),
        Paragraph(
            "<b>Scan to Verify Report</b>",
            normal_style,
        ),
    ]

    report_header = Table(
        [[header_title, qr_flowable]],
        colWidths=[150 * mm, 25 * mm],
    )

    report_header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )

    story.append(report_header)

    header_data = [
        [
            Paragraph("<b>Report ID</b>", normal_style),
            Paragraph(_value(report_id), normal_style),
            Paragraph("<b>Report Date</b>", normal_style),
            Paragraph(
                _format_date(session.get("created_at")),
                normal_style,
            ),
        ],
        [
            Paragraph("<b>Session No.</b>", normal_style),
            Paragraph(_value(session.get("session_number")), normal_style),
            Paragraph("<b>Test Type</b>", normal_style),
            Paragraph(_value(session.get("test_type")), normal_style),
        ],
        [
            Paragraph("<b>Test Location</b>", normal_style),
            Paragraph(_value(session.get("test_location")), normal_style),
            Paragraph("<b>Status</b>", normal_style),
            Paragraph(_value(session.get("status")), normal_style),
        ],
    ]

    header_table = Table(
        header_data,
        colWidths=[30 * mm, 57 * mm, 30 * mm, 57 * mm],
    )

    header_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F2F2F2")),
                ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F2F2F2")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )

    story.append(header_table)

    # ---------------------------------------------------------
    # INSTRUMENT DETAILS
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "1. Instrument Identification",
            section_style,
        )
    )

    instrument_data = [
        [
            Paragraph("<b>Manufacturer</b>", normal_style),
            Paragraph(_value(instrument.get("manufacturer")), normal_style),
            Paragraph("<b>Model</b>", normal_style),
            Paragraph(_value(instrument.get("model")), normal_style),
        ],
        [
            Paragraph("<b>Serial Number</b>", normal_style),
            Paragraph(_value(instrument.get("serial_number")), normal_style),
            Paragraph("<b>Instrument Type</b>", normal_style),
            Paragraph(_value(instrument.get("instrument_type")), normal_style),
        ],
        [
            Paragraph("<b>Accuracy Class</b>", normal_style),
            Paragraph(_value(instrument.get("accuracy_class")), normal_style),
            Paragraph("<b>Unit</b>", normal_style),
            Paragraph(_value(instrument.get("unit")), normal_style),
        ],
        [
            Paragraph("<b>Max Capacity</b>", normal_style),
            Paragraph(_value(instrument.get("max_capacity")), normal_style),
            Paragraph("<b>Min Capacity</b>", normal_style),
            Paragraph(_value(instrument.get("min_capacity")), normal_style),
        ],
        [
            Paragraph("<b>Verification Scale Interval (e)</b>", normal_style),
            Paragraph(_value(instrument.get("verification_scale_interval_e")), normal_style),
            Paragraph("<b>Actual Scale Interval (d)</b>", normal_style),
            Paragraph(_value(instrument.get("actual_scale_interval_d")), normal_style),
        ],
        [
            Paragraph("<b>Number of Intervals (n)</b>", normal_style),
            Paragraph(_value(instrument.get("number_of_verification_scale_intervals_n")), normal_style),
            Paragraph("<b>Type Approval No.</b>", normal_style),
            Paragraph(_value(instrument.get("type_approval_number")), normal_style),
        ],
        [
            Paragraph("<b>Software Version</b>", normal_style),
            Paragraph(_value(instrument.get("software_version")), normal_style),
            Paragraph("<b>Year of Manufacture</b>", normal_style),
            Paragraph(_value(instrument.get("year_of_manufacture")), normal_style),
        ],
    ]

    instrument_table = Table(
        instrument_data,
        colWidths=[43 * mm, 44 * mm, 43 * mm, 44 * mm],
    )

    instrument_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F7F7F7")),
                ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F7F7F7")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    story.append(instrument_table)

    # ---------------------------------------------------------
    # STANDARD
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "2. Reference Standard",
            section_style,
        )
    )

    story.append(
        Paragraph(
            "Testing and compliance evaluation performed with reference to "
            "<b>OIML Recommendation R 76 — Non-Automatic Weighing Instruments</b> "
            "and the applicable rule definitions configured in OIMLense.",
            normal_style,
        )
    )

    # ---------------------------------------------------------
    # ENVIRONMENT
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "3. Laboratory / Environmental Conditions",
            section_style,
        )
    )

    env = environment[0] if environment else {}

    environment_data = [
        [
            Paragraph("<b>Ambient Temperature</b>", normal_style),
            Paragraph(_value(env.get("ambient_temperature")), normal_style),
            Paragraph("<b>Relative Humidity</b>", normal_style),
            Paragraph(_value(env.get("relative_humidity")), normal_style),
        ],
        [
            Paragraph("<b>Atmospheric Pressure</b>", normal_style),
            Paragraph(_value(env.get("atmospheric_pressure")), normal_style),
            Paragraph("<b>Supply Voltage</b>", normal_style),
            Paragraph(_value(env.get("supply_voltage")), normal_style),
        ],
        [
            Paragraph("<b>Supply Frequency</b>", normal_style),
            Paragraph(_value(env.get("supply_frequency")), normal_style),
            Paragraph("<b>Tilt Condition</b>", normal_style),
            Paragraph(_value(env.get("tilt_condition")), normal_style),
        ],
        [
            Paragraph("<b>Stabilization Time</b>", normal_style),
            Paragraph(
                _value(env.get("stabilization_time_minutes")),
                normal_style,
            ),
            Paragraph("<b>Other Conditions</b>", normal_style),
            Paragraph(_value(env.get("other_conditions")), normal_style),
        ],
    ]

    environment_table = Table(
        environment_data,
        colWidths=[43 * mm, 44 * mm, 43 * mm, 44 * mm],
    )

    environment_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F7F7F7")),
                ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F7F7F7")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    story.append(environment_table)

    # ---------------------------------------------------------
    # EQUIPMENT
    # ---------------------------------------------------------

    if equipment:
        story.append(
            Paragraph(
                "4. Test Equipment",
                section_style,
            )
        )

        equipment_rows = [
            [
                Paragraph("<b>Name</b>", small_style),
                Paragraph("<b>Type</b>", small_style),
                Paragraph("<b>Manufacturer</b>", small_style),
                Paragraph("<b>Model</b>", small_style),
                Paragraph("<b>Serial No.</b>", small_style),
                Paragraph("<b>Calibration</b>", small_style),
            ]
        ]

        for item in equipment:
            equipment_rows.append(
                [
                    Paragraph(_value(item.get("name")), small_style),
                    Paragraph(_value(item.get("equipment_type")), small_style),
                    Paragraph(_value(item.get("manufacturer")), small_style),
                    Paragraph(_value(item.get("model")), small_style),
                    Paragraph(_value(item.get("serial_number")), small_style),
                    Paragraph(_value(item.get("calibration_id")), small_style),
                ]
            )

        equipment_table = Table(
            equipment_rows,
            colWidths=[
                32 * mm,
                27 * mm,
                31 * mm,
                28 * mm,
                30 * mm,
                30 * mm,
            ],
            repeatRows=1,
        )

        equipment_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 3),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )

        story.append(equipment_table)

    # ---------------------------------------------------------
    # TEST RESULTS
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "5. Test Results",
            section_style,
        )
    )

    result_rows = [
        [
            Paragraph("<b>#</b>", small_style),
            Paragraph("<b>Test / Rule</b>", small_style),
            Paragraph("<b>Measured Error</b>", small_style),
            Paragraph("<b>MPE / Limit</b>", small_style),
            Paragraph("<b>Clause</b>", small_style),
            Paragraph("<b>Result</b>", small_style),
        ]
    ]

    for index, result in enumerate(results, start=1):
        calculated = result.get("calculated_values") or {}

        test_name = (
            calculated.get("test_name")
            or result.get("rule_id")
            or result.get("test_definition_id")
            or "R76 Test"
        )

        measured_error = result.get("measured_error")

        mpe_value = result.get("mpe_value")

        clause = result.get("source_clause")

        status = _result_status(result.get("result_status"))

        result_rows.append(
            [
                Paragraph(str(index), small_style),
                Paragraph(_value(test_name), small_style),
                Paragraph(_value(measured_error), small_style),
                Paragraph(_value(mpe_value), small_style),
                Paragraph(_value(clause), small_style),
                Paragraph(status, small_style),
            ]
        )

    if len(result_rows) == 1:
        result_rows.append(
            [
                Paragraph("—", small_style),
                Paragraph("No test results recorded", small_style),
                Paragraph("—", small_style),
                Paragraph("—", small_style),
                Paragraph("—", small_style),
                Paragraph("MANUAL REVIEW", small_style),
            ]
        )

    results_table = Table(
        result_rows,
        colWidths=[
            10 * mm,
            61 * mm,
            29 * mm,
            29 * mm,
            27 * mm,
            25 * mm,
        ],
        repeatRows=1,
    )

    result_style_commands = [
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]

    for row_index, result in enumerate(results, start=1):
        status = _result_status(result.get("result_status"))

        if status == "PASS":
            background = colors.HexColor("#EAF6EC")
        elif status == "FAIL":
            background = colors.HexColor("#FBEAEA")
        else:
            background = colors.HexColor("#FFF7DD")

        result_style_commands.append(
            (
                "BACKGROUND",
                (5, row_index),
                (5, row_index),
                background,
            )
        )

    results_table.setStyle(TableStyle(result_style_commands))

    story.append(results_table)

    # ---------------------------------------------------------
    # OBSERVATIONS
    # ---------------------------------------------------------

    if observations:
        story.append(
            Paragraph(
                "6. Test Observations",
                section_style,
            )
        )

        observation_rows = [
            [
                Paragraph("<b>#</b>", small_style),
                Paragraph("<b>Load Applied</b>", small_style),
                Paragraph("<b>Indication Before</b>", small_style),
                Paragraph("<b>Indication After</b>", small_style),
                Paragraph("<b>Error</b>", small_style),
                Paragraph("<b>Position</b>", small_style),
            ]
        ]

        for index, item in enumerate(observations, start=1):
            observation_rows.append(
                [
                    Paragraph(str(index), small_style),
                    Paragraph(_value(item.get("load_applied")), small_style),
                    Paragraph(_value(item.get("indication_before")), small_style),
                    Paragraph(_value(item.get("indication_after")), small_style),
                    Paragraph(_value(item.get("error_observed")), small_style),
                    Paragraph(_value(item.get("position")), small_style),
                ]
            )

        observations_table = Table(
            observation_rows,
            colWidths=[
                10 * mm,
                31 * mm,
                35 * mm,
                35 * mm,
                29 * mm,
                38 * mm,
            ],
            repeatRows=1,
        )

        observations_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 3),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )

        story.append(observations_table)

    # ---------------------------------------------------------
    # FINAL COMPLIANCE DECISION
    # ---------------------------------------------------------

    overall = _overall_result(session, results)

    story.append(
        Paragraph(
            "7. Final Compliance Decision",
            section_style,
        )
    )

    decision_data = [
        [
            Paragraph("<b>Overall Result</b>", normal_style),
            Paragraph(
                f"<b>{overall}</b>",
                normal_style,
            ),
        ],
        [
            Paragraph("<b>Number of Tests</b>", normal_style),
            Paragraph(str(len(results)), normal_style),
        ],
        [
            Paragraph("<b>Tests Passed</b>", normal_style),
            Paragraph(
                str(
                    sum(
                        1
                        for item in results
                        if str(item.get("result_status") or "").upper() == "PASS"
                    )
                ),
                normal_style,
            ),
        ],
        [
            Paragraph("<b>Tests Failed</b>", normal_style),
            Paragraph(
                str(
                    sum(
                        1
                        for item in results
                        if str(item.get("result_status") or "").upper() == "FAIL"
                    )
                ),
                normal_style,
            ),
        ],
    ]

    decision_table = Table(
        decision_data,
        colWidths=[60 * mm, 118 * mm],
    )

    decision_background = (
        "#EAF6EC"
        if overall == "PASS"
        else "#FBEAEA"
        if overall == "FAIL"
        else "#FFF7DD"
    )

    decision_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BBBBBB")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F2F2F2")),
                ("BACKGROUND", (1, 0), (1, 0), colors.HexColor(decision_background)),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story.append(decision_table)

    # ---------------------------------------------------------
    # TRACEABILITY
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "8. Regulatory Traceability",
            section_style,
        )
    )

    trace_text = (
        "The individual test results in this report are linked to the "
        "corresponding OIMLense R76 test definitions, rule identifiers, "
        "source clauses and configured rule versions where available. "
        "The calculations are generated by the deterministic OIMLense R76 "
        "calculation engine."
    )

    story.append(
        Paragraph(
            trace_text,
            normal_style,
        )
    )

    # ---------------------------------------------------------
    # DECLARATION / SIGNATURE
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "9. Review and Approval",
            section_style,
        )
    )

    signature_data = [
        [
            Paragraph("<b>Tested By</b>", normal_style),
            Paragraph("<b>Reviewed By</b>", normal_style),
            Paragraph("<b>Approved By</b>", normal_style),
        ],
        [
            Paragraph(
                _value(session.get("officer_user_id")),
                normal_style,
            ),
            Paragraph(
                _value(session.get("reviewer_user_id")),
                normal_style,
            ),
            Paragraph(
                _value(session.get("approver_user_id")),
                normal_style,
            ),
        ],
        [
            Paragraph("Signature: ____________________", small_style),
            Paragraph("Signature: ____________________", small_style),
            Paragraph("Signature: ____________________", small_style),
        ],
    ]

    signature_table = Table(
        signature_data,
        colWidths=[59 * mm, 59 * mm, 60 * mm],
        rowHeights=[9 * mm, 12 * mm, 16 * mm],
    )

    signature_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F2F2F2")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )

    story.append(signature_table)

    story.append(Spacer(1, 8 * mm))

    story.append(
        Paragraph(
            "This document is electronically generated by OIMLense. "
            "Final approval and legal validity remain subject to the "
            "authorized laboratory / officer review process.",
            small_style,
        )
    )

    document.build(
        story,
        onFirstPage=_header_footer,
        onLaterPages=_header_footer,
    )

    buffer.seek(0)

    return buffer
